CREATE TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    description text,
    priority INTEGER NOT NULL,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    project_id INTEGER REFERENCES projects(id)
);

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a Web App', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make an App', 1, 'Using Dark', '2019-05-13');

INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a Desktop App', 1, 'Using C++', '2019-05-14');

-- Insert task data
INSERT INTO tasks (name, done, project_id)
VALUES ('Download Vuejs', false, 1);

INSERT INTO tasks (name, done, project_id)
VALUES ('Create UI Web', false, 1);

INSERT INTO tasks (name, done, project_id)
VALUES ('Download Flutter', false, 2);

INSERT INTO tasks (name, done, project_id)
VALUES ('Design UI', false, 2);